/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type TreeSelector_TreeFragment = {
  link: string
  name: Maybe<string>
  quantity: number
  children: Maybe<
    Array<Maybe<{ link: string; name: Maybe<string>; quantity: number }>>
  >
}

// Query Related Code
