
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type ShippingQueryQueryVariables = Exact<{
  items: Maybe<Array<Maybe<Vtex_ShippingItem>>>;
  postalCode: Maybe<Scalars['String']>;
  country: Maybe<Scalars['String']>;
}>;


export type ShippingQueryQuery = { vtex: { shippingSLA: Maybe<{ countries: Maybe<Array<Maybe<string>>>, deliveryOptions: Array<{ estimate: string, price: number }> }> } };


// Query Related Code

export const ShippingQuery = {
  query: "query ShippingQuery($items: [VTEX_ShippingItem], $postalCode: String, $country: String) {\n  vtex {\n    shippingSLA(items: $items, postalCode: $postalCode, country: $country) {\n      countries\n      deliveryOptions {\n        estimate\n        price\n      }\n    }\n  }\n}\n",
  sha256Hash: "bada983651a7b0c3d8ae0fd43329737ee116307c15fb3c57e134025ff50e6fcc",
  operationName: "ShippingQuery",
}

