
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type ClearOrderFormMessagesMutationMutationVariables = Exact<{
  orderFormId: Maybe<Scalars['ID']>;
}>;


export type ClearOrderFormMessagesMutationMutation = { clearOrderFormMessages: { id: string } };


// Query Related Code

export const ClearOrderFormMessagesMutation = {
  query: process.env.NODE_ENV === 'production' ? undefined : "mutation ClearOrderFormMessagesMutation($orderFormId: ID) {\n  clearOrderFormMessages(orderFormId: $orderFormId) {\n    id\n  }\n}\n",
  sha256Hash: "77e02ce38118308f49ee176ab82d6269d11fed12ed8d72a3364b1cfe2e882f2d",
  operationName: "ClearOrderFormMessagesMutation",
}

