# .coderabbit.yaml
# Valid configuration for CodeRabbit – FastStore friendly

language: en

reviews:
  profile: chill
  comment_style: inline

  high_level_summary: true
  auto_approve: false
  max_comments: 15

  ignore:
    - "**/*.snap"
    - "**/*.lock"
    - "**/dist/**"
    - "**/.next/**"
    - "**/generated/**"

  # Extra context to guide the reviewer (THIS IS VALID)
  instructions: |
    This is a FastStore (VTEX) project.
    Focus reviews on:
    - Performance (Core Web Vitals)
    - Accessibility basics (a11y)
    - Architectural consistency
    - Production impact over stylistic preferences

    Avoid:
    - Obvious comments
    - Formatting nitpicks
    - Repeating what linters already catch
