# .coderabbit.yaml
# Recommended configuration for FastStore (VTEX) projects

language: "en"

reviews:
  # Avoid obvious or repetitive comments
  profile: "chill"

  # Inline comments on PRs
  comment_style: "inline"

  # High-level summary instead of noise
  high_level_summary: true
  auto_approve: false

  # Limit comments to keep reviews actionable
  max_comments: 15

  # Ignore generated or low-value files
  ignore:
    - "**/*.snap"
    - "**/*.lock"
    - "**/dist/**"
    - "**/.next/**"
    - "**/generated/**"

rules:
  # Architecture and project structure
  - name: "FastStore Architecture"
    description: "Ensure alignment with FastStore and VTEX architectural standards"
    severity: "high"
    keywords:
      - "pages/"
      - "components/"
      - "sections/"
      - "sdk/"
      - "store.config"

  # Performance is critical for e-commerce
  - name: "Performance and Core Web Vitals"
    description: "Prevent negative impact on LCP, CLS, and TBT"
    severity: "high"
    keywords:
      - "useEffect"
      - "useMemo"
      - "useCallback"
      - "Image"
      - "lazy"
      - "dynamic import"

  # Accessibility baseline
  - name: "Accessibility"
    description: "Check for basic accessibility best practices"
    severity: "medium"
    keywords:
      - "aria-"
      - "alt="
      - "role="
      - "label"

  # Maintainability and DX
  - name: "Readability and Developer Experience"
    description: "Clear, predictable, and maintainable code"
    severity: "medium"
    keywords:
      - "any"
      - "TODO"
      - "FIXME"

guidelines:
  # Explicit review tone
  tone: "constructive and direct"
  focus:
    - "production impact"
    - "user experience"
    - "architectural consistency"
    - "FastStore standards"

  avoid:
    - "obvious comments"
    - "formatting nitpicks"
    - "contextless suggestions"

knowledge:
  # Project context
  framework: "FastStore"
  platform: "VTEX"
  stack:
    - "React"
    - "TypeScript"
    - "Next.js"
    - "GraphQL"
    - "Tailwind or CSS Modules"

tools:
  lint: true
  typescript: true
  performance_hints: true
