packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/ni': 0.21.12
  '@envelop/core': ^5
  '@envelop/graphql-jit': ^11
  '@envelop/parser-cache': ^10
  '@envelop/testing': ^10
  '@envelop/validation-cache': ^10
  '@graphql-codegen/cli': 5.0.2
  '@graphql-codegen/typescript': 4.0.7
  '@graphql-tools/merge': 9.1.1
  '@graphql-tools/schema': 10.0.25
  '@graphql-tools/utils': 10.10.1
  '@jest/globals': 29.7.0
  '@next/third-parties': ^15.5.3
  '@playwright/test': ^1.55.0
  '@testing-library/react': ^14.3.0
  '@types/jest': 29.1.0
  '@types/node': 20.19.13
  '@types/react': ^18
  '@types/react-dom': ^18
  '@types/tabbable': ^3.1.1
  cookie: ^0.7.0
  fast-deep-equal: ^3.1.3
  graphql: 16.11.0
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  next: ^13
  react: ^18
  react-dom: ^18
  react-intersection-observer: ^8.32.5
  react-swipeable: ^7.0.0
  tabbable: 5.2.1
  ts-jest: 29.1.1
  tslib: 2.8.1
  typescript: 5.9.3
  vite: 7.1.5
  vite-plugin-dts: 4.5.4
  vitest: 4.0.7

overrides:
  graphql: 16.11.0
  typescript: 5.9.3
