/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type UseBestSeller_SkuFragment = {
  sellers: Maybe<
    Array<
      Maybe<{
        commertialOffer: Maybe<{
          AvailableQuantity: Maybe<number>
          Price: Maybe<number>
        }>
      }>
    >
  >
}

// Query Related Code
