/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type UseAsyncProductQueryQueryVariables = Exact<{
  slug: Maybe<Scalars['String']>
}>

export type UseAsyncProductQueryQuery = {
  vtex: {
    product: Maybe<{
      productId: Maybe<string>
      productName: Maybe<string>
      description: Maybe<string>
      linkText: Maybe<string>
      items: Maybe<
        Array<
          Maybe<{
            itemId: Maybe<string>
            images: Maybe<
              Array<
                Maybe<{ imageUrl: Maybe<string>; imageText: Maybe<string> }>
              >
            >
            sellers: Maybe<
              Array<
                Maybe<{
                  commertialOffer: Maybe<{
                    AvailableQuantity: Maybe<number>
                    ListPrice: Maybe<number>
                    Price: Maybe<number>
                  }>
                }>
              >
            >
          }>
        >
      >
    }>
  }
}

// Query Related Code

export const useAsyncProductQuery = {
  query:
    'query useAsyncProductQuery($slug: String) {\n  vtex {\n    product(slug: $slug) {\n      productId\n      productName\n      description\n      linkText\n      items {\n        itemId\n        images {\n          imageUrl\n          imageText\n        }\n        sellers {\n          commertialOffer {\n            AvailableQuantity\n            ListPrice\n            Price\n          }\n        }\n      }\n    }\n  }\n}\n',
  sha256Hash:
    'ee5bffe7a8504361512c12f21f5f8017bd7341c2f54215c0f72eafad10ae7ebf',
  operationName: 'useAsyncProductQuery',
}
