
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type SuggestionsQueryQueryVariables = Exact<{
  fullText: Scalars['String'];
  regionId: Maybe<Scalars['String']>;
  facetKey: Maybe<Scalars['String']>;
  facetValue: Maybe<Scalars['String']>;
  simulationBehavior?: Maybe<Vtex_SimulationBehavior>;
}>;


export type SuggestionsQueryQuery = { vtex: { productSuggestions: Maybe<{ total: number, products: Array<Maybe<{ productName: Maybe<string>, linkText: Maybe<string>, brand: Maybe<string>, productReference: Maybe<string>, id: Maybe<string>, categoryTree: Maybe<Array<Maybe<{ name: Maybe<string> }>>>, productClusters: Maybe<Array<Maybe<{ id: Maybe<string>, name: Maybe<string> }>>>, properties: Maybe<Array<Maybe<{ name: Maybe<string>, originalName: Maybe<string>, values: Maybe<Array<Maybe<string>>> }>>>, items: Maybe<Array<Maybe<{ itemId: Maybe<string>, name: Maybe<string>, measurementUnit: Maybe<string>, unitMultiplier: Maybe<number>, referenceId: Maybe<Array<Maybe<{ value: Maybe<string> }>>>, images: Maybe<Array<Maybe<{ imageUrl: Maybe<string>, imageText: Maybe<string> }>>>, sellers: Maybe<Array<Maybe<{ sellerId: Maybe<string>, commercialOffer: Maybe<{ spotPrice: Maybe<number>, availableQuantity: Maybe<number>, price: Maybe<number>, listPrice: Maybe<number>, maxInstallments: Maybe<Array<Maybe<{ value: Maybe<number>, numberOfInstallments: Maybe<number> }>>>, installments: Maybe<Array<Maybe<{ value: Maybe<number>, numberOfInstallments: Maybe<number>, interestRate: Maybe<number> }>>>, teasers: Maybe<Array<{ name: Maybe<string> }>> }> }>>> }>>> }>> }> } };


// Query Related Code

export const SuggestionsQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query SuggestionsQuery($fullText: String!, $regionId: String, $facetKey: String, $facetValue: String, $simulationBehavior: VTEX_SimulationBehavior = default) {\n  vtex {\n    productSuggestions(\n      fullText: $fullText\n      regionId: $regionId\n      facetKey: $facetKey\n      facetValue: $facetValue\n      simulationBehavior: $simulationBehavior\n    ) {\n      total: count\n      products {\n        id: productId\n        productName\n        linkText\n        brand\n        productReference\n        categoryTree {\n          name\n        }\n        productClusters {\n          id\n          name\n        }\n        properties {\n          name\n          originalName\n          values\n        }\n        items {\n          itemId\n          name\n          referenceId {\n            value: Value\n          }\n          images {\n            imageUrl\n            imageText\n          }\n          measurementUnit\n          unitMultiplier\n          sellers {\n            sellerId\n            commercialOffer: commertialOffer {\n              maxInstallments: Installments(criteria: MAX_WITHOUT_INTEREST) {\n                value: Value\n                numberOfInstallments: NumberOfInstallments\n              }\n              installments: Installments(criteria: ALL) {\n                value: Value\n                numberOfInstallments: NumberOfInstallments\n                interestRate: InterestRate\n              }\n              availableQuantity: AvailableQuantity\n              price: Price\n              listPrice: ListPrice\n              spotPrice\n              teasers {\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n",
  sha256Hash: "4f51d211533221c61c4ffc0c6807dc6522410e0b136295662e01eccc8a3a2741",
  operationName: "SuggestionsQuery",
}

