/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type SearchPageQueryQueryVariables = Exact<{
  query: Maybe<Scalars['String']>
  map: Maybe<Scalars['String']>
  staticPath?: Maybe<Scalars['Boolean']>
}>

export type SearchPageQueryQuery = {
  vtex: {
    productSearch: Maybe<{
      titleTag: Maybe<string>
      breadcrumb: Maybe<
        Array<Maybe<{ href: Maybe<string>; name: Maybe<string> }>>
      >
      products: Maybe<
        Array<
          Maybe<{
            productId: Maybe<string>
            productName: Maybe<string>
            description: Maybe<string>
            linkText: Maybe<string>
            items: Maybe<
              Array<
                Maybe<{
                  itemId: Maybe<string>
                  images: Maybe<
                    Array<
                      Maybe<{
                        imageUrl: Maybe<string>
                        imageText: Maybe<string>
                      }>
                    >
                  >
                  sellers: Maybe<
                    Array<
                      Maybe<{
                        sellerId: Maybe<string>
                        commertialOffer: Maybe<{
                          AvailableQuantity: Maybe<number>
                          Price: Maybe<number>
                          ListPrice: Maybe<number>
                        }>
                      }>
                    >
                  >
                }>
              >
            >
          }>
        >
      >
    }>
    facets: Maybe<{
      brands: Maybe<
        Array<Maybe<{ name: string; value: string; quantity: number }>>
      >
      categoriesTrees: Maybe<
        Array<
          Maybe<{
            link: string
            name: Maybe<string>
            quantity: number
            children: Maybe<
              Array<
                Maybe<{ link: string; name: Maybe<string>; quantity: number }>
              >
            >
          }>
        >
      >
    }>
  }
}

// Query Related Code

export const SearchPageQuery = {
  query: undefined,
  sha256Hash:
    '379b53aab4e983247d48127f96777ed3fd13f3e90cf1e77b0a67314ea576045e',
  operationName: 'SearchPageQuery',
}
