export { default } from './Modal'
export { default as ModalHeader } from './ModalHeader'
export { default as ModalBody } from './ModalBody'
export type { ModalProps } from './Modal'
export type { ModalHeaderProps } from './ModalHeader'
