/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type ProductRecommendationsQueryQueryVariables = Exact<{
  value: Scalars['ID']
}>

export type ProductRecommendationsQueryQuery = {
  vtex: {
    productRecommendations: Maybe<
      Array<
        Maybe<{
          productId: Maybe<string>
          productName: Maybe<string>
          linkText: Maybe<string>
          productClusters: Maybe<Array<Maybe<{ name: Maybe<string> }>>>
          items: Maybe<
            Array<
              Maybe<{
                itemId: Maybe<string>
                images: Maybe<
                  Array<
                    Maybe<{ imageUrl: Maybe<string>; imageText: Maybe<string> }>
                  >
                >
                sellers: Maybe<
                  Array<
                    Maybe<{
                      sellerId: Maybe<string>
                      commercialOffer: Maybe<{
                        spotPrice: Maybe<number>
                        availableQuantity: Maybe<number>
                        price: Maybe<number>
                        listPrice: Maybe<number>
                        maxInstallments: Maybe<
                          Array<
                            Maybe<{
                              value: Maybe<number>
                              numberOfInstallments: Maybe<number>
                            }>
                          >
                        >
                        installments: Maybe<
                          Array<
                            Maybe<{
                              value: Maybe<number>
                              numberOfInstallments: Maybe<number>
                              interestRate: Maybe<number>
                            }>
                          >
                        >
                        teasers: Maybe<Array<{ name: Maybe<string> }>>
                      }>
                    }>
                  >
                >
              }>
            >
          >
        }>
      >
    >
  }
}

// Query Related Code

export const ProductRecommendationsQuery = {
  query: undefined,
  sha256Hash:
    'b71a91102538e2d04e10ca1c5d8b5fe57c68cab6b25e61d17d31537ced191c21',
  operationName: 'ProductRecommendationsQuery',
}
