/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type ShelfQueryQueryVariables = Exact<{
  query: Maybe<Scalars['String']>
  map: Maybe<Scalars['String']>
  selectedFacets: Maybe<Vtex_SelectedFacetInput[]>
  fullText: Maybe<Scalars['String']>
  from: Maybe<Scalars['Int']>
  to: Maybe<Scalars['Int']>
  orderBy: Maybe<Scalars['String']>
}>

export type ShelfQueryQuery = {
  vtex: {
    productSearch: Maybe<{
      products: Maybe<
        Array<
          Maybe<{
            productId: Maybe<string>
            productName: Maybe<string>
            description: Maybe<string>
            linkText: Maybe<string>
            items: Maybe<
              Array<
                Maybe<{
                  itemId: Maybe<string>
                  images: Maybe<
                    Array<
                      Maybe<{
                        imageUrl: Maybe<string>
                        imageText: Maybe<string>
                      }>
                    >
                  >
                  sellers: Maybe<
                    Array<
                      Maybe<{
                        sellerId: Maybe<string>
                        commertialOffer: Maybe<{
                          AvailableQuantity: Maybe<number>
                          Price: Maybe<number>
                          ListPrice: Maybe<number>
                        }>
                      }>
                    >
                  >
                }>
              >
            >
          }>
        >
      >
    }>
  }
}

// Query Related Code

export const ShelfQuery = {
  query:
    'query ShelfQuery($query: String, $map: String, $selectedFacets: [VTEX_SelectedFacetInput!], $fullText: String, $from: Int, $to: Int, $orderBy: String) {\n  vtex {\n    productSearch(query: $query, map: $map, selectedFacets: $selectedFacets, fullText: $fullText, from: $from, to: $to, orderBy: $orderBy) {\n      products {\n        productId\n        productName\n        description\n        linkText\n        items {\n          itemId\n          images {\n            imageUrl\n            imageText\n          }\n          sellers {\n            sellerId\n            commertialOffer {\n              AvailableQuantity\n              Price\n              ListPrice\n            }\n          }\n        }\n      }\n    }\n  }\n}\n',
  sha256Hash:
    '3bbb0a016127e310c09cf5f04bb358edcba3fcd34ff96e8b457f5a2d0ae504ec',
  operationName: 'ShelfQuery',
}
