/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type TopSearchesSuggestionsQueryQueryVariables = Exact<{
  [key: string]: never
}>

export type TopSearchesSuggestionsQueryQuery = {
  vtex: {
    topSearches: Maybe<{
      searches: Maybe<Array<Maybe<{ term: string; key: string }>>>
    }>
  }
}

// Query Related Code

export const TopSearchesSuggestionsQuery = {
  query:
    'query TopSearchesSuggestionsQuery {\n  vtex {\n    topSearches {\n      searches {\n        term\n        key: term\n      }\n    }\n  }\n}\n',
  sha256Hash:
    '0f17502d9ac8f6d58c692554521e07ab9dd0f6094271196bd3c9d37207dabeef',
  operationName: 'TopSearchesSuggestionsQuery',
}
