
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type SearchPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type SearchPageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, titleTemplate: Maybe<string>, siteUrl: Maybe<string>, description: Maybe<string>, author: Maybe<string> }> }> };


// Query Related Code

export const SearchPageSEOQuery = {
  query: undefined,
  sha256Hash: "78467c58ecaaf9bd3b276104e60367355ce000d298fac563bf7f6c7b2d1e7d18",
  operationName: "SearchPageSEOQuery",
}

