
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type SiteMetadataQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type SiteMetadataQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, siteUrl: Maybe<string>, description: Maybe<string>, author: Maybe<string> }> }> };


// Query Related Code

export const SiteMetadataQuery = {
  query: "query SiteMetadataQuery {\n  site {\n    siteMetadata {\n      title\n      siteUrl\n      description\n      author\n    }\n  }\n}\n",
  sha256Hash: "ae693f9e4e249574090ecbdaa1a61624c9614449ac30611a18e74621a0099b9b",
  operationName: "SiteMetadataQuery",
}

