/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type SetRegionMutationMutationVariables = Exact<{
  postalCode: Maybe<Scalars['String']>;
  country?: Maybe<Scalars['String']>;
  addressType?: Maybe<Vtex_AddressType>;
  orderFormId: Maybe<Scalars['ID']>;
}>;


export type SetRegionMutationMutation = { updateSelectedAddress: { id: string, shipping: { availableAddresses: Maybe<Array<Maybe<{ postalCode: Maybe<string>, receiverName: Maybe<string>, reference: Maybe<string>, state: Maybe<string>, street: Maybe<string>, number: Maybe<string>, neighborhood: Maybe<string>, isDisposable: Maybe<boolean>, geoCoordinates: Maybe<Array<Maybe<number>>>, country: Maybe<string>, complement: Maybe<string>, city: Maybe<string>, addressType: Maybe<Vtex_AddressType>, addressId: Maybe<string> }>>>, selectedAddress: Maybe<{ addressId: Maybe<string>, addressType: Maybe<Vtex_AddressType>, city: Maybe<string>, complement: Maybe<string>, country: Maybe<string>, geoCoordinates: Maybe<Array<Maybe<number>>>, isDisposable: Maybe<boolean>, neighborhood: Maybe<string>, postalCode: Maybe<string>, number: Maybe<string>, receiverName: Maybe<string>, reference: Maybe<string>, state: Maybe<string>, street: Maybe<string> }> } } };


// Query Related Code

export const SetRegionMutation = {
  query: process.env.NODE_ENV === 'production' ? undefined : "mutation SetRegionMutation($postalCode: String, $country: String = \"BRA\", $addressType: VTEX_AddressType = residential, $orderFormId: ID) {\n  updateSelectedAddress(\n    input: {postalCode: $postalCode, country: $country, addressType: $addressType}\n    orderFormId: $orderFormId\n  ) {\n    id\n    shipping {\n      availableAddresses {\n        postalCode\n        receiverName\n        reference\n        state\n        street\n        number\n        neighborhood\n        isDisposable\n        geoCoordinates\n        country\n        complement\n        city\n        addressType\n        addressId\n      }\n      selectedAddress {\n        addressId\n        addressType\n        city\n        complement\n        country\n        geoCoordinates\n        isDisposable\n        neighborhood\n        postalCode\n        number\n        receiverName\n        reference\n        state\n        street\n      }\n    }\n  }\n}\n",
  sha256Hash: "88123433bae328c5343786600d75a4860f4465dd6281e02ea9e17c8fd8d57a62",
  operationName: "SetRegionMutation",
}

