module.exports = {
  seo: {
    title: 'FastStore',
    description: 'A fast and performant store framework',
    titleTemplate: '%s | FastStore',
    author: 'FastStore',
    name: 'FastStore',
    publisherId: '',
    plp: {
      titleTemplate: '%s | FastStore PLP',
      descriptionTemplate: '%s products on FastStore Product Listing Page',
    },
    pdp: {
      titleTemplate: '%s | FastStore PDP',
      descriptionTemplate: '%s products on FastStore Product Detail Page',
    },
    search: {
      titleTemplate: '%s: Search results title',
      descriptionTemplate: '%s: Search results description',
      noIndex: true,
      noFollow: true,
      bodyH1: 'Showing results for:',
    },
  },
  theme: 'custom-theme',
  platform: 'vtex',
  api: {
    storeId: 'newstore',
    workspace: 'master',
    subDomainPrefix: ['www'],
    environment: 'vtexcommercestable',
    hideUnavailableItems: true,
    showSponsored: false,
    incrementAddress: false,
    enableUnavailableItemsOnCart: false,
  },
  session: {
    currency: {
      code: 'BRL',
      symbol: 'R$',
    },
    locale: 'pt-BR',
    channel: '{"salesChannel":"1","regionId":""}',
    country: 'BRA',
    deliveryMode: null,
    addressType: null,
    city: null,
    postalCode: null,
    geoCoordinates: null,
    b2b: null,
    person: null,
    marketingData: {
      utmCampaign: '',
      utmMedium: '',
      utmSource: '',
      utmiCampaign: '',
      utmiPart: '',
      utmiPage: '',
    },
    refreshAfter: null,
  },
  cart: {
    id: '',
    items: [],
    messages: [],
    shouldSplitItem: true,
  },
  storeUrl: 'https://www.fast.store',
  secureSubdomain: 'https://www.fast.store/',
  checkoutUrl: 'https://www.fast.store/checkout',
  loginUrl: 'https://www.fast.store/api/io/login',
  accountUrl: 'https://www.fast.store/api/io/account',
  previewRedirects: {
    404: '/404',
    500: '/500',
    home: '/',
    plp: '/headphones',
    search: '/s?q=Newstore',
    pdp: '/headphone-white-10000006/p',
  },
  lighthouse: {
    server: 'http://localhost:3000',
    pages: {
      home: '/',
      pdp: '/headphone-white-10000006/p',
      collection: '/headphones',
    },
  },
  analytics: {
    gtmContainerId: 'GTM-1234567',
  },
  cms: {},
  contentSource: {
    type: 'CMS',
  },
  deliveryPromise: {
    enabled: false,
    mandatory: false,
  },
  experimental: {
    noRobots: false,
    noindex: false,
    nofollow: false,
    preact: false,
    enableRedirects: false,
    enableSearchSSR: false,
    enableFaststoreMyAccount: true,
    enableVtexAssetsLoader: false,
    graphqlCacheControl: {
      maxAge: 0,
      staleWhileRevalidate: 60,
    },
    refreshToken: false,
    nodeVersion: 18,
  },
  vtexHeadlessCms: {
    webhookUrls: ['https://newstore.myvtex.com/cms-releases/webhook-releases'],
  },
}
