module.exports = {
  seo: {
    title: 'FastStore Starter',
    description: 'Fast Demo Store',
    titleTemplate: '%s | FastStore',
    name: 'FastStore',
    publisherId: '',
    plp: {
      titleTemplate: '%s | FastStore PLP',
      descriptionTemplate: '%s products on FastStore Product Listing Page',
    },
    pdp: {
      titleTemplate: '%s | FastStore PDP',
      descriptionTemplate: '%s products on FastStore Product Detail Page',
    },
    search: {
      titleTemplate: '%s | Search results',
      descriptionTemplate: '%s Search results description',
      noIndex: true,
      noFollow: true,
      bodyH1: 'Showing results for:',
    },
  },
  theme: 'custom-theme',
  platform: 'vtex',
  api: {
    storeId: 'brandless',
    workspace: 'master',
    subDomainPrefix: ['www'],
    environment: 'vtexcommercestable',
    hideUnavailableItems: false,
    showSponsored: false,
    incrementAddress: true,
    enableUnavailableItemsOnCart: false,
  },
  session: {
    currency: {
      code: 'USD',
      symbol: '$',
    },
    locale: 'pt-BR',
    channel:
      '{"salesChannel":"1","regionId":"","hasOnlyDefaultSalesChannel":"true"}',
    country: 'USA',
    deliveryMode: null,
    addressType: null,
    city: null,
    postalCode: null,
    geoCoordinates: null,
    b2b: null,
    person: null,
    marketingData: {
      utmCampaign: '',
      utmMedium: '',
      utmSource: '',
      utmiCampaign: '',
      utmiPart: '',
      utmiPage: '',
    },
    refreshAfter: null,
  },
  localization: {
    enabled: true,
    defaultLocale: 'pt-BR',
    regions: {
      US: {
        code: 'US',
        name: 'United States',
        dateFormat: 'MM/DD/YYYY',
        timeFormat: '12h',
        timeFormatMask: 'hh:mm a',
        unitSystem: 'imperial',
        defaultTimezone: 'GMT-5',
      },
      BR: {
        code: 'BR',
        name: 'Brazil',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: '24h',
        timeFormatMask: 'HH:mm',
        unitSystem: 'metric',
        defaultTimezone: 'GMT-3',
      },
    },
    locales: {
      'pt-BR': {
        code: 'pt-BR',
        name: 'português',
        languageCode: 'pt',
        languageName: 'Portuguese',
        script: 'Latn',
        textDirection: 'ltr',
        regionCode: 'BR',
        bindings: [
          {
            currencyCode: 'BRL',
            url: 'http://localhost:3000/pt-BR',
            salesChannel: '1',
            isDefault: true,
          },
        ],
      },
      'en-US': {
        code: 'en-US',
        name: 'English',
        languageCode: 'en',
        languageName: 'English',
        script: 'Latn',
        textDirection: 'ltr',
        regionCode: 'US',
        bindings: [
          {
            currencyCode: 'USD',
            url: 'http://localhost:3000/en-US',
            salesChannel: '2',
            isDefault: false,
          },
        ],
      },
    },
    currencies: {
      BRL: {
        code: 'BRL',
        name: 'Brazilian Real',
        symbol: 'R$',
      },
      USD: {
        code: 'USD',
        name: 'US Dollar',
        symbol: '$',
      },
    },
  },
  cart: {
    id: '',
    items: [],
    messages: [],
    shouldSplitItem: true,
  },
  storeUrl: 'https://homebrewqa.fast.store',
  secureSubdomain: 'https://homebrewqa.fast.store',
  checkoutUrl: 'https://homebrewqa.fast.store/checkout',
  loginUrl: 'https://homebrewqa.fast.store/api/io/login',
  accountUrl: 'https://homebrewqa.fast.store/api/io/account',
  previewRedirects: {
    404: '/404',
    500: '/500',
    home: '/',
    plp: '/office',
    search: '/s?q=headphone',
    pdp: '/apple-magic-mouse/p',
  },
  lighthouse: {
    server: 'http://localhost:3000',
    pages: {
      home: '/',
      pdp: '/4k-philips-monitor-99988213/p',
      collection: '/office',
    },
  },
  cypress: {
    pages: {
      home: '/',
      pdp: '/4k-philips-monitor-99988213/p',
      collection: '/office',
      collection_2: '/technology',
      collection_filtered:
        '/office/?category-1=office&marca=acer&facets=category-1%2Cmarca',
      search: '/s?q=orange',
    },
  },
  analytics: {
    gtmContainerId: 'GTM-PGHZ95N',
  },
  cms: {},
  contentSource: {
    type: 'CP',
  },
  deliveryPromise: {
    enabled: false,
    mandatory: false,
  },
  experimental: {
    cypressVersion: 12,
    enableCypressExtension: false,
    noRobots: false,
    noindex: false,
    nofollow: false,
    preact: false,
    enableRedirects: false,
    enableSearchSSR: false,
    enableFaststoreMyAccount: false,
    graphqlCacheControl: {
      maxAge: 0,
      staleWhileRevalidate: 3600,
    },
    refreshToken: false,
    scrollRestoration: false,
    cachedOperations: [
      'ServerAccountPageQuery',
      'ServerCollectionPageQuery',
      'ServerProductQuery',
      'ServerOrderDetailsQuery',
      'ServerListOrdersQuery',
      'ServerProfileQuery',
      'ServerSecurity',
      'ServerUserDetailsQuery',
      'ValidateUser',
      'ClientPickupPointsQuery',
      'ClientProductCountQuery',
      'ClientAllVariantProductsQuery',
      'ClientManyProductsQuery',
      'ClientProductGalleryQuery',
      'ClientProductQuery',
      'ClientManyProductsSelectedQuery',
      'ClientProfileQuery',
      'ClientSearchSuggestionsQuery',
      'ClientTopSearchSuggestionsQuery',
      'ClientShippingSimulationQuery',
      'ServerManyProductsQuery',
    ],
  },
  direction: 'ltr',
}
