module.exports = {
  seo: {
    title: 'B2B Faststore',
    description: 'A fast and performant store framework',
    titleTemplate: '%s | B2B FastStore',
    name: 'FastStore',
    publisherId: '',
    author: 'b2bfaststore',
    plp: {
      titleTemplate: '%s | FastStore PLP',
      descriptionTemplate: '%s products on FastStore Product Listing Page',
    },
    pdp: {
      titleTemplate: '%s | FastStore PDP',
      descriptionTemplate: '%s products on FastStore Product Detail Page',
      minPriceAmountFractionDigits: undefined,
    },
    search: {
      titleTemplate: '%s | Search results',
      descriptionTemplate: '%s Search results description',
      noIndex: true,
      noFollow: true,
      bodyH1: 'Showing results for:',
    },
  },

  // Theming
  theme: 'custom-theme',

  // Ecommerce Platform
  platform: 'vtex',

  // Platform specific configs for API
  api: {
    storeId: 'b2bfaststoredev',
    workspace: 'master',
    subDomainPrefix: ['www'],
    environment: 'vtexcommercestable',
    hideUnavailableItems: true,
    showSponsored: false,
    incrementAddress: false,
    enableUnavailableItemsOnCart: false,
  },

  // Default session
  session: {
    currency: {
      code: 'BRL',
      symbol: 'R$',
    },
    locale: 'en-US',
    channel: '{"salesChannel":1,"regionId":""}',
    country: 'USA',
    deliveryMode: null,
    addressType: null,
    city: null,
    postalCode: null,
    geoCoordinates: null,
    b2b: null,
    person: null,
    marketingData: {
      utmCampaign: '',
      utmMedium: '',
      utmSource: '',
      utmiCampaign: '',
      utmiPart: '',
      utmiPage: '',
    },
    refreshAfter: null, // timestamp in seconds e.g. '1743042990'
  },

  // Default cart
  cart: {
    id: '',
    items: [],
    messages: [],
    shouldSplitItem: true,
  },

  // Production URLs
  // secureSubdomain is the same as storeUrl because we are using single domain approach for this account
  storeUrl: 'https://b2bfaststore.vtexfaststore.com',
  secureSubdomain: 'https://b2bfaststore.vtexfaststore.com',
  checkoutUrl:
    process.env.NODE_ENV === 'development'
      ? 'http://localhost:3000/checkout/cart'
      : 'https://b2bfaststore.vtexfaststore.com/checkout',
  loginUrl: 'https://b2bfaststore.vtexfaststore.com/api/io/login',
  accountUrl: 'https://b2bfaststore.vtexfaststore.com/api/io/account',

  // Preview redirects
  previewRedirects: {
    404: '/404',
    500: '/500',
    home: '/',
    plp: '/category',
    search: '/s?q=Precision%20Pro',
    pdp: '/combination-spanner-set-storage2/p',
  },

  // Lighthouse CI
  lighthouse: {
    server: process.env.BASE_SITE_URL || 'http://localhost:3000',
    pages: {
      home: '/',
      pdp: '/combination-spanner-set-storage2/p',
      collection: '/category',
    },
  },

  // E2E CI
  cypress: {
    pages: {
      home: '/',
      pdp: '/combination-spanner-set-storage2/p',
      collection: '/category',
      collection_2: '/technology',
      collection_filtered:
        '/category/?category-1=category&brand=Precision%20Pro&facets=category-1%2Cbrand%27',
      search: '/s?q=Precision%20Pro',
    },
    browser: 'electron',
  },

  analytics: {
    // https://developers.google.com/tag-platform/tag-manager/web#standard_web_page_installation,
    gtmContainerId: '',
    serviceName: 'faststore-proxy',
    otelEnabled: true,
  },

  cms: {
    data: process.env.CMS_DATA,
  },

  contentSource: {
    type: 'CMS',
  },

  deliveryPromise: {
    enabled: false,
    mandatory: false,
  },

  // Localization feature flag
  localization: {
    enabled: false,

    // generated by @faststore/cli when localization is enabled
    defaultLocale: 'pt-BR',
    regions: {
      BR: {
        code: 'BR',
        name: 'Brazil',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: '12h',
        timeFormatMask: 'hh:mm a',
        unitSystem: 'metric',
        defaultTimezone: 'GMT-3',
      },
    },
    locales: {
      'en-US': {
        bindings: [
          {
            url: 'https://b2bfaststore.vtexfaststore.com',
            salesChannel: '1',
            isDefault: true,
          },
        ],
      },
    },
    currencies: {
      BRL: {
        code: 'BRL',
        name: 'Brazilian Real',
        symbol: 'R$',
      },
    },
  },

  experimental: {
    nodeVersion: 24,
    cypressVersion: 12,
    enableCypressExtension: false,
    enableScriptsLogs: false,
    noRobots: false,
    noindex: false,
    nofollow: false,
    preact: false,
    enableRedirects: false,
    enableSearchSSR: false,
    enableFaststoreMyAccount: true,
    useIsGiftFromOrderForm: false,
    graphqlCacheControl: {
      maxAge: 0, // 0 disables cache, 5 * 60 enable cache control maxAge 5 minutes
      staleWhileRevalidate: 60 * 60, // 1 hour
    },
    refreshToken: false,
    scrollRestoration: false,
    /** Package names to transpile (e.g. ['@vtex/components']). Use a non-empty list to enable Next.js transpilation. */
    transpilePackages: [],
  },

  // Text direction: 'ltr' (left-to-right) or 'rtl' (right-to-left)
  direction: 'ltr',

  vtexHeadlessCms: {
    webhookUrls: [
      'https://b2bfaststoredev.myvtex.com/cms-releases/webhook-releases',
    ],
  },
}
