const path = require('node:path')
const storeConfig = require('./discovery.config')
const { buildI18nDomains } = require('./scripts/i18n')

// Load locales settings (generated by CLI during build)
const localesSettings = storeConfig.localization

const getRootFolder = () => {
  if (__dirname.endsWith('.faststore')) return path.join(__dirname, '..')

  return path.join(__dirname, '../../')
}

console.log(`
  Root folder at: ${getRootFolder()}
  AccountID: ${storeConfig.api?.storeId ?? 'Unknown'}
  Analytics Enabled: ${storeConfig.analytics?.otelEnabled ?? false}
`)

const optimizedFontsEnabled = storeConfig.experimental?.optimizedFonts === true

// Self-hosted Inter font (opt-in via experimental.optimizedFonts).
//
// We append the @fontsource/inter weight stylesheets to the global stylesheet
// (src/styles/main.scss) through Sass's additionalData. Sass passes these plain
// CSS @imports through untouched and css-loader inlines them into main.scss's
// own chunk — the global stylesheet that Next links on every page — so the
// @font-face rules and the .woff2 assets ship together. Plain CSS imports (not
// next/font) keep this compiler-agnostic (works with both Babel and SWC).
const interFontFaceImports = [400, 500, 600, 700, 900]
  .map((weight) => `@import '@fontsource/inter/${weight}.css';`)
  .join('\n')

// Scoped to main.scss only: returning the content untouched for every other
// stylesheet avoids duplicating the @font-face rules into each CSS module.
// Appended (never prepended) so the imports land after main.scss's leading
// @use rules, which Sass requires to come first.
const appendInterFontsToGlobalStylesheet = (content, loaderContext) => {
  const resourcePath = (loaderContext?.resourcePath ?? '').replace(/\\/g, '/')
  const isGlobalStylesheet = resourcePath.endsWith('/src/styles/main.scss')

  return isGlobalStylesheet ? `${content}\n${interFontFaceImports}` : content
}

/**
 * @type {import('next').NextConfig}
 * */
const nextConfig = {
  /* config options here */
  /* Replaces terser by swc for minifying. It's the default in NextJS 13 */
  swcMinify: true,
  ...(Array.isArray(storeConfig.experimental?.transpilePackages) &&
    storeConfig.experimental.transpilePackages.length > 0 && {
      transpilePackages: storeConfig.experimental.transpilePackages,
    }),
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: `${storeConfig.api.storeId}.vtexassets.com`,
        pathname: '/**',
      },
    ],
    deviceSizes: [360, 412, 540, 768, 1280, 1440],
    imageSizes: [34, 68, 154, 320],
    loader: 'custom',
    loaderFile: './src/components/ui/Image/loader.ts',
  },
  i18n: localesSettings.enabled
    ? {
        locales: Object.keys(localesSettings.locales || {}),
        defaultLocale: localesSettings.defaultLocale,
        localeDetection: false,
        domains: buildI18nDomains(localesSettings),
      }
    : {
        locales: [storeConfig.session.locale],
        defaultLocale: storeConfig.session.locale,
      },
  sassOptions: {
    silenceDeprecations: ['if-function', 'legacy-js-api'],
    ...(optimizedFontsEnabled && {
      additionalData: appendInterFontsToGlobalStylesheet,
    }),
  },
  // TODO: We won't need to enable this experimental feature when migrating to Next.js 13
  experimental: {
    instrumentationHook: true,
    scrollRestoration: !storeConfig.experimental.scrollRestoration,
  },
  /*
   * The FastStore Discovery CLI will update this value to match the path where the
   * command is being run, because that is where the node_modules directory is.
   * For discovery-only paths, that is the user directory, and for monorepo, that is the base
   * of the monorepo
   * */
  outputFileTracingRoot: getRootFolder(),
  webpack: (config, { isServer, dev }) => {
    // https://github.com/vercel/next.js/discussions/11267#discussioncomment-2479112
    // camel-case style names from css modules
    config.module.rules
      .find(({ oneOf }) => !!oneOf)
      .oneOf.filter(({ use }) => JSON.stringify(use)?.includes('css-loader'))
      .reduce((acc, { use }) => acc.concat(use), [])
      .forEach(({ options }) => {
        if (options.modules) {
          options.modules.exportLocalsConvention = 'camelCase'
        }
      })

    // Reduce the number of chunks so we ship a smaller first bundle.
    // This should help reducing TBT
    if (!isServer && !dev && config.optimization?.splitChunks) {
      config.optimization.splitChunks.maxInitialRequests = 1
    }

    return config
  },
  redirects: storeConfig.redirects,
  rewrites: storeConfig.rewrites,
  turbopack: {
    root: getRootFolder(),
    // https://nextjs.org/docs/app/api-reference/turbopack#css-module-ordering
    resolveAlias: {
      '~*': '*',
    },
  },
}

module.exports = nextConfig
