/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type ProductsSuggestionsQueryQueryVariables = Exact<{
  fullText: Scalars['String']
  facetKey: Maybe<Scalars['String']>
  facetValue: Maybe<Scalars['String']>
  productOriginVtex?: Maybe<Scalars['Boolean']>
  simulationBehavior?: Maybe<Vtex_SimulationBehavior>
}>

export type ProductsSuggestionsQueryQuery = {
  vtex: {
    productSuggestions: Maybe<{
      count: number
      products: Array<
        Maybe<{
          productId: Maybe<string>
          productName: Maybe<string>
          description: Maybe<string>
          linkText: Maybe<string>
          key: Maybe<string>
          items: Maybe<
            Array<
              Maybe<{
                itemId: Maybe<string>
                images: Maybe<
                  Array<
                    Maybe<{ imageUrl: Maybe<string>; imageText: Maybe<string> }>
                  >
                >
                sellers: Maybe<
                  Array<
                    Maybe<{
                      sellerId: Maybe<string>
                      commercialOffer: Maybe<{
                        availableQuantity: Maybe<number>
                        price: Maybe<number>
                        listPrice: Maybe<number>
                      }>
                    }>
                  >
                >
              }>
            >
          >
        }>
      >
    }>
  }
}

// Query Related Code

export const ProductsSuggestionsQuery = {
  query:
    'query ProductsSuggestionsQuery($fullText: String!, $facetKey: String, $facetValue: String, $productOriginVtex: Boolean = false, $simulationBehavior: VTEX_SimulationBehavior = default) {\n  vtex {\n    productSuggestions(fullText: $fullText, facetKey: $facetKey, facetValue: $facetValue, productOriginVtex: $productOriginVtex, simulationBehavior: $simulationBehavior) {\n      count\n      products {\n        key: productId\n        productId\n        productName\n        description\n        linkText\n        items {\n          itemId\n          images {\n            imageUrl\n            imageText\n          }\n          sellers {\n            sellerId\n            commercialOffer: commertialOffer {\n              availableQuantity: AvailableQuantity\n              price: Price\n              listPrice: ListPrice\n            }\n          }\n        }\n      }\n    }\n  }\n}\n',
  sha256Hash:
    '8bebf0498101ef93ac5be449eb63b4964412cb936dbe667ca2ff4119fe87dff5',
  operationName: 'ProductsSuggestionsQuery',
}
