/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
}

// Operation related types
export type AsyncProductQueryQueryVariables = Exact<{
  slug: Maybe<Scalars['String']>
}>

export type AsyncProductQueryQuery = {
  vtex: {
    product: Maybe<{
      productId: Maybe<string>
      productName: Maybe<string>
      description: Maybe<string>
      linkText: Maybe<string>
      items: Maybe<
        Array<
          Maybe<{
            itemId: Maybe<string>
            images: Maybe<
              Array<
                Maybe<{ imageUrl: Maybe<string>; imageText: Maybe<string> }>
              >
            >
            sellers: Maybe<
              Array<
                Maybe<{
                  commercialOffer: Maybe<{
                    availableQuantity: Maybe<number>
                    listPrice: Maybe<number>
                    price: Maybe<number>
                  }>
                }>
              >
            >
          }>
        >
      >
    }>
  }
}

// Query Related Code

export const AsyncProductQuery = {
  query: undefined,
  sha256Hash:
    '81c7db6fb5c82a66e0176452be6e43057593bcb5df40583ea33004e64dc96138',
  operationName: 'AsyncProductQuery',
}
