
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type ProductPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type ProductPageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, titleTemplate: Maybe<string>, siteUrl: Maybe<string>, description: Maybe<string>, author: Maybe<string> }> }> };


// Query Related Code

export const ProductPageSEOQuery = {
  query: undefined,
  sha256Hash: "622ef2a0fa8091aed1c191ceb132b5e9665ca28e47bdcc5e70eba6a4788c0191",
  operationName: "ProductPageSEOQuery",
}

