
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type AutocompleteSuggestionsQueryQueryVariables = Exact<{
  fullText: Scalars['String'];
}>;


export type AutocompleteSuggestionsQueryQuery = { vtex: { autocompleteSearchSuggestions: Maybe<{ searches: Maybe<Array<Maybe<{ term: string }>>> }> } };


// Query Related Code

export const AutocompleteSuggestionsQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query AutocompleteSuggestionsQuery($fullText: String!) {\n  vtex {\n    autocompleteSearchSuggestions(fullText: $fullText) {\n      searches {\n        term\n      }\n    }\n  }\n}\n",
  sha256Hash: "0a7c20eadfee9296a47a4e9e1e0062b7aeac1f8ad2fda4e7f11681b0fe56b60a",
  operationName: "AutocompleteSuggestionsQuery",
}

