
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type HomePageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type HomePageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, siteUrl: Maybe<string>, description: Maybe<string>, author: Maybe<string> }> }> };


// Query Related Code

export const HomePageSEOQuery = {
  query: undefined,
  sha256Hash: "69f363d6650b5b3fcd98586ac8296ce49b53b6e7684f13d491a8ae9f7e99b800",
  operationName: "HomePageSEOQuery",
}
