name: Packages Preview

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: FastStore
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    permissions:
      id-token: write # Required if using OIDC
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::053131491888:role/diagnostics-gh-actions-role
          aws-region: us-east-1

      - name: Set CodeArtifact Auth
        run: |
          CA_TOKEN=$(aws codeartifact get-authorization-token --domain main --domain-owner 053131491888 --region us-east-1 --query authorizationToken --output text)
          echo "CA_TOKEN=$CA_TOKEN" >> $GITHUB_ENV

      - name: Preinstall
        run: pnpm run preinstall

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build
      - run: pnpm dlx pkg-pr-new publish './packages/*' --no-compact --packageManager=yarn --commentWithSha
