/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type SiteMetadataQueryQueryVariables = Exact<{ [key: string]: never }>

export type SiteMetadataQueryQuery = {
  site: Maybe<{
    siteMetadata: Maybe<{
      title: Maybe<string>
      description: Maybe<string>
      author: Maybe<string>
    }>
  }>
}

// Query Related Code

export const SiteMetadataQuery = {
  query: undefined,
  sha256Hash:
    '38817674a7094b82cd30fd470268fe7e22c99de447b81ed2bf32f6c4fe65cc80',
  operationName: 'SiteMetadataQuery',
}
