import { Providers } from './providers'

// FastStore UI's base styles
import '../styles/global/index.scss'
import '../plugins/index.scss'
import '../customizations/src/themes/index.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="theme">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
